version: "3.8"
services:
  reverse-proxy:
    depends_on:
      - blog
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile_reverse-proxy
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    volumes:
      - wordpress:/var/www/html
      - wiki:/var/www/wiki
  masters:
    build:
      context: .
      dockerfile: Dockerfile_masters
    expose:
      - "3000"
    ports:
      - "8001:3000"
#   volumes:
#     - .:/cadre:cached

  db_blog:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: somewordpresspassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    command: '--default-authentication-plugin=mysql_native_password'

  blog:
    depends_on:
      - db_blog
    image: wordpress:5.5.3-php7.2-fpm
    expose:
      - "9000"
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db_blog:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html
  
  wiki:
    image: mediawiki:1.35.0
    restart: always
    ports:
      - 9080:80
    volumes:
      - wiki:/var/www/html/images
      - ./LocalSettings.php:/var/www/html/mw-config/LocalSettings.php

  farmos:
    image: farmos/farmos:7.x-1.6
#    volumes:
#      - ./sites:/var/www/html/sites
    ports:
      - '9876:80'

volumes:
  db_data:
  wordpress:
  wiki:
