version: "3.8"
services:
  reverse-proxy:
    build:
      context: .
      dockerfile: Dockerfile_reverse-proxy
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host

  app:
    build:
      context: .
      dockerfile: Dockerfile_app
    expose:
      - "3000"
#   ports:
#     - "8001:3000"
#   volumes:
#     - .:/cadre:cached
