version: "3.8"
services:
  reverse-proxy:
    build:
      context: .
      dockerfile: Dockerfile_reverse-proxy
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host

  app:
    build:
      context: .
      dockerfile: Dockerfile_app
    expose:
      - "3000"
#   ports:
#     - "8001:3000"
#   volumes:
#     - .:/cadre:cached

  db_blog:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpresspassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  blog:
    depends_on:
      - db_blog
    image: wordpress:5.5.3-php7.2-fpm
    expose:
      - "8000"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

volumes:
  db_data:
